// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8c92qf8iwF2sqdrrSaFbXdIg0OW5StFg',
    appId: '1:525921291285:web:de039bf1e0d19d6990521c',
    messagingSenderId: '525921291285',
    projectId: 'fruits-9a06a',
    authDomain: 'fruits-9a06a.firebaseapp.com',
    storageBucket: 'fruits-9a06a.firebasestorage.app',
    measurementId: 'G-L4MTEVVHE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwZkD-wZ_ZKEs43U5SxiXKjwWPX9mWQZI',
    appId: '1:525921291285:android:8b4fb707a42323cd90521c',
    messagingSenderId: '525921291285',
    projectId: 'fruits-9a06a',
    storageBucket: 'fruits-9a06a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt_5KephnJlgWWrDxL1YvRLb9Fo5WmbKo',
    appId: '1:525921291285:ios:091b8d48457f674f90521c',
    messagingSenderId: '525921291285',
    projectId: 'fruits-9a06a',
    storageBucket: 'fruits-9a06a.firebasestorage.app',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt_5KephnJlgWWrDxL1YvRLb9Fo5WmbKo',
    appId: '1:525921291285:ios:091b8d48457f674f90521c',
    messagingSenderId: '525921291285',
    projectId: 'fruits-9a06a',
    storageBucket: 'fruits-9a06a.firebasestorage.app',
    iosBundleId: 'com.example.fruits',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8c92qf8iwF2sqdrrSaFbXdIg0OW5StFg',
    appId: '1:525921291285:web:8495570c9103a85690521c',
    messagingSenderId: '525921291285',
    projectId: 'fruits-9a06a',
    authDomain: 'fruits-9a06a.firebaseapp.com',
    storageBucket: 'fruits-9a06a.firebasestorage.app',
    measurementId: 'G-5379ZZZSWM',
  );
}
